# Build image for Latex

FROM ubuntu:22.04

MAINTAINER Elliott Slaughter <slaughter@cs.stanford.edu>

ENV DEBIAN_FRONTEND noninteractive

COPY . /build

RUN apt-get update -qq && \
    apt-get install -qq git make texlive texlive-fonts-extra && \
    apt-get clean

RUN cd /build && make
